//! Hidden-value CONSTRAINT SYSTEM — migration steps 1–2 of
//! `notes/HIDDEN_VALUE_PROPAGATION_NOTES.md`.
//!
//! v1 (`hidden.rs`) is a forward rewriting closure: known values generate
//! known values. This module recasts the same knowledge as an F2-LINEAR
//! SYSTEM over entries of the hidden map blocks ([`HiddenVar`]), solved with
//! plain Gaussian elimination:
//!
//! - every value in the v1 closure (assertions + Toda-P deductions, with
//!   IDENTICAL gate semantics — the closure is literally generated by
//!   [`crate::hidden::HiddenStore::propagate`], so the two can never drift)
//!   becomes a pinned linear combination `Σ_j x_j·M[i,j] = y_i`;
//! - the solver then reasons ACROSS values: dim-1 blocks pin their single
//!   entry, overlapping combos determine further entries, and conflicting
//!   assertions surface as UNSAT instead of silently coexisting — the
//!   backward direction v1 cannot do.
//!
//! v1 is kept as the REGRESSION ORACLE: [`solve_hidden`] verifies that every
//! closure value's combination is determined by the solved system with the
//! right value (kernel-orthogonality + offset check). That check is
//! tautological today (each combo is pinned directly) and load-bearing
//! tomorrow: any future constraint family (exactness, more Toda relations,
//! backward links) that accidentally contradicts or weakens the forward
//! closure trips it.
//!
//! Step 2 (report-only): [`exactness_deficiencies`] recomputes the fiber
//! diagnostics' rank bookkeeping in Rust — cells on the terminal page where
//! `rank(incoming) < dim ker(outgoing)`, i.e. where EXACTNESS FORCES a
//! hidden EHP value to exist. Guards: every involved degree must be
//! in-window, un-excluded, and away from the max_t frontier, mirroring (a
//! conservative version of) the python panel's window/frontier guards.
//! Nothing is enforced yet; the report is meant to be eyeballed against the
//! pink `fiber_hidden` candidates in the fiber charts.
//!
//! Deferred (tier 3 / step 3+): recording possibility-set linear hulls and
//! exactness constraints into a per-page `recorded_constraints` channel fed
//! to `build_constraint_system` — ONE channel shared with the possibility-
//! set consensus (see the notes addendum), with the usual quarantine +
//! dim-guard treatment. Not built here.

use fp::vector::FpVector;
use hashbrown::HashMap;

use crate::element::Element;
use crate::gf2::*;
use crate::hidden::{hidden_enabled, HiddenStore};
use crate::map::MapKind;
use crate::page::SATPage;
use crate::tridegree::Tridegree;

/// Entry `[row, col]` of the hidden part of map `kind` at source degree
/// `deg`, filtration jump `delta ≥ 1`: `col` indexes the source basis,
/// `row` the basis at the nominal target degree raised by `delta`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct HiddenVar {
    pub kind: MapKind,
    pub deg: Tridegree,
    pub delta: i32,
    pub row: u16,
    pub col: u16,
}

impl std::fmt::Display for HiddenVar {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}_h({},{},{})[δ={}][{},{}]",
            self.kind, self.deg.n, self.deg.s, self.deg.f, self.delta, self.row, self.col
        )
    }
}

/// Outcome of one [`solve_hidden`] run.
pub struct HiddenSolveReport {
    pub num_vars: usize,
    pub num_constraints: usize,
    /// `false` = the assertions (plus their Toda closure) are mutually
    /// inconsistent as linear statements — some asserted value is wrong.
    pub consistent: bool,
    /// Individually determined hidden ENTRIES (kernel-free coordinates).
    pub determined: Vec<(HiddenVar, bool)>,
    /// Of those, the ones no single closure value pins on its own (i.e. the
    /// solver's added value over the forward closure).
    pub beyond_closure: Vec<(HiddenVar, bool)>,
    /// v1-oracle verdict: every closure value's combination is determined
    /// with the matching value. Must be `true` whenever `consistent`.
    pub oracle_ok: bool,
    pub oracle_failures: Vec<String>,
    pub warnings: Vec<String>,
    /// Size of the v1 closure the system was built from.
    pub closure_len: usize,
}

/// Build and solve the hidden-value linear system from the store's ASSERTED
/// values (their Toda-P closure is regenerated via v1's own propagation, so
/// gate semantics are identical by construction).
pub fn solve_hidden(page: &SATPage, store: &HiddenStore) -> HiddenSolveReport {
    let mut warnings = Vec::new();

    // v1 closure from the assertions only (fresh store, same rule code).
    let mut closure_store = HiddenStore::new();
    let mut closure: Vec<(MapKind, Element, Element)> = Vec::new();
    if hidden_enabled() {
        for hv in store.asserted() {
            match closure_store.assert_value(page, hv.kind, hv.source.clone(), hv.target.clone())
            {
                Ok(_) => {}
                Err(e) => warnings.push(format!("assertion {} rejected: {}", hv, e)),
            }
        }
        let (_, notes) = closure_store.propagate(page);
        warnings.extend(notes);
        closure = closure_store
            .iter()
            .map(|hv| (hv.kind, hv.source.clone(), hv.target.clone()))
            .collect();
    }

    // Register the full variable block of every degree/δ a closure value
    // touches, then pin each value's linear combination.
    let mut vars: Vec<HiddenVar> = Vec::new();
    let mut index: HashMap<HiddenVar, usize> = HashMap::new();
    let ensure_block = |kind: MapKind,
                            deg: Tridegree,
                            delta: i32,
                            page: &SATPage,
                            vars: &mut Vec<HiddenVar>,
                            index: &mut HashMap<HiddenVar, usize>|
     -> (usize, usize) {
        let src_dim = page.dim_at(deg);
        let nominal = kind.target_degree(deg);
        let tgt_dim = page.dim_at(Tridegree::new(nominal.n, nominal.s, nominal.f + delta));
        for row in 0..tgt_dim {
            for col in 0..src_dim {
                let v = HiddenVar {
                    kind,
                    deg,
                    delta,
                    row: row as u16,
                    col: col as u16,
                };
                index.entry(v).or_insert_with(|| {
                    vars.push(v);
                    vars.len() - 1
                });
            }
        }
        (src_dim, tgt_dim)
    };

    let mut cons: Vec<(Vec<usize>, bool)> = Vec::new();
    // For each closure value: rows `Σ_{j ∈ supp(x)} M[i,j] = y_i`.
    for (kind, x, y) in &closure {
        let delta = y.degree.f - kind.target_degree(x.degree).f;
        let (src_dim, tgt_dim) =
            ensure_block(*kind, x.degree, delta, page, &mut vars, &mut index);
        if x.vec.len() != src_dim || y.vec.len() != tgt_dim {
            warnings.push(format!(
                "closure value {}({}) = {} skipped: stale dimensions",
                kind, x, y
            ));
            continue;
        }
        let support: Vec<usize> = vec_support(&x.vec).collect();
        for i in 0..tgt_dim {
            let idxs: Vec<usize> = support
                .iter()
                .map(|&j| {
                    index[&HiddenVar {
                        kind: *kind,
                        deg: x.degree,
                        delta,
                        row: i as u16,
                        col: j as u16,
                    }]
                })
                .collect();
            cons.push((idxs, vec_get(&y.vec, i)));
        }
    }

    // Solve the XOR system with plain Gauss (the system is small — blocks
    // reachable from assertions only).
    let n = vars.len();
    let rows: Vec<FpVector> = cons
        .iter()
        .map(|(idxs, _)| {
            let mut row = vec_zero(n);
            for &i in idxs {
                vec_flip(&mut row, i);
            }
            row
        })
        .collect();
    let mut rhs = vec_zero(cons.len());
    for (i, (_, val)) in cons.iter().enumerate() {
        vec_set(&mut rhs, i, *val);
    }
    let m = mat_from_rows(&rows, n);
    let g = gauss_solve(&m, &rhs);

    if !g.consistent {
        return HiddenSolveReport {
            num_vars: n,
            num_constraints: cons.len(),
            consistent: false,
            determined: Vec::new(),
            beyond_closure: Vec::new(),
            oracle_ok: false,
            oracle_failures: vec!["system UNSAT — assertions mutually inconsistent".into()],
            warnings,
            closure_len: closure.len(),
        };
    }

    let offset = g.solution.expect("consistent gauss has a solution");
    // Free coordinates = union of kernel supports (same convention as the
    // differential solver post-fix: correlated pivots are NOT determined).
    let mut free = vec![false; n];
    for k in &g.kernel {
        for i in vec_support(k) {
            free[i] = true;
        }
    }
    let mut determined: Vec<(HiddenVar, bool)> = Vec::new();
    for (i, v) in vars.iter().enumerate() {
        if !free[i] {
            determined.push((*v, vec_get(&offset, i)));
        }
    }

    // Entries pinned by a single closure value directly (support-1 combo on
    // a single row): everything else in `determined` is solver-added value.
    let mut directly_pinned: HashMap<usize, bool> = HashMap::new();
    for (idxs, val) in &cons {
        if idxs.len() == 1 {
            directly_pinned.insert(idxs[0], *val);
        }
    }
    let beyond_closure: Vec<(HiddenVar, bool)> = determined
        .iter()
        .filter(|(v, _)| !directly_pinned.contains_key(&index[v]))
        .copied()
        .collect();

    // Oracle: every closure value's combination must be determined (each of
    // its rows orthogonal to the kernel) with the recorded value.
    let mut oracle_failures = Vec::new();
    for (kind, x, y) in &closure {
        let delta = y.degree.f - kind.target_degree(x.degree).f;
        let support: Vec<usize> = vec_support(&x.vec).collect();
        for i in 0..y.vec.len() {
            let mut combo = vec_zero(n);
            let mut ok = true;
            for &j in &support {
                match index.get(&HiddenVar {
                    kind: *kind,
                    deg: x.degree,
                    delta,
                    row: i as u16,
                    col: j as u16,
                }) {
                    Some(&idx) => vec_flip(&mut combo, idx),
                    None => ok = false,
                }
            }
            if !ok {
                continue; // skipped stale value, already warned
            }
            if g.kernel.iter().any(|k| vec_dot(k, &combo)) {
                oracle_failures.push(format!(
                    "{}({}) = {} row {}: combination is FREE in the solved system",
                    kind, x, y, i
                ));
            } else if vec_dot(&offset, &combo) != vec_get(&y.vec, i) {
                oracle_failures.push(format!(
                    "{}({}) = {} row {}: solved value differs from closure value",
                    kind, x, y, i
                ));
            }
        }
    }

    HiddenSolveReport {
        num_vars: n,
        num_constraints: cons.len(),
        consistent: true,
        determined,
        beyond_closure,
        oracle_ok: oracle_failures.is_empty(),
        oracle_failures,
        warnings,
        closure_len: closure.len(),
    }
}

// ---------------------------------------------------------------------------
// Step 2 (report-only): exactness deficiencies on the terminal page
// ---------------------------------------------------------------------------

/// A fiber-sequence cell where the terminal page's nominal maps cannot be
/// exact: `rank(incoming) < dim ker(outgoing)` at `middle`, so `deficiency`
/// independent classes are neither hit by the incoming map nor mapped
/// anywhere by the outgoing one — exactness of the underlying homotopy
/// sequence FORCES hidden values here. This is the rank bookkeeping behind
/// the fiber charts' pink `fiber_hidden` candidates, computed engine-side.
#[derive(Clone, Debug)]
pub struct ExactnessDeficiency {
    pub base_n: i32,
    pub incoming: MapKind,
    pub outgoing: MapKind,
    pub source: Tridegree,
    pub middle: Tridegree,
    pub rank_in: usize,
    pub dim_ker_out: usize,
    pub deficiency: usize,
    /// Asserted/deduced hidden values already landing at (or leaving) the
    /// middle degree — candidates that may resolve the deficiency.
    pub hidden_at_cell: usize,
}

fn mat_rank(m: &fp::matrix::Matrix) -> usize {
    let mut basis: Vec<FpVector> = Vec::new();
    for i in 0..m.rows() {
        let mut row = mat_get_row(m, i);
        for b in &basis {
            if let Some(lead) = vec_first_set(b) {
                if vec_get(&row, lead) {
                    vec_xor_assign(&mut row, b);
                }
            }
        }
        if !vec_is_zero(&row) {
            basis.push(row);
        }
    }
    basis.len()
}

/// Enumerate exactness deficiencies on `page` (intended for the terminal
/// page). Guards, conservative versions of the python panel's: every degree
/// of the square (source, middle, outgoing target) must have s ≥ 0, be
/// unexcluded, sit at least `frontier_margin` below the page's max_t, and
/// the middle must have positive dimension.
pub fn exactness_deficiencies(
    page: &SATPage,
    store: &HiddenStore,
    frontier_margin: i32,
) -> Vec<ExactnessDeficiency> {
    let mut out = Vec::new();
    let Some(max_t) = page.max_t else {
        return out;
    };
    let in_window = |t: Tridegree| -> bool {
        t.s >= 0 && t.f >= 0 && t.n >= 2 && t.s + t.f <= max_t - frontier_margin
    };

    // Cells indexed like the fiber view: base sphere N, chain anchor (σ, f).
    let mut base_ns: Vec<i32> = page
        .page
        .keys()
        .map(|t| t.n)
        .filter(|&n| n >= 2)
        .collect();
    base_ns.sort_unstable();
    base_ns.dedup();

    for &base_n in &base_ns {
        for sigma in 0..=max_t {
            for f in 0..=max_t {
                if sigma + f > max_t {
                    break;
                }
                for sq in crate::fiber::exactness_squares(base_n, sigma, f) {
                    let src = crate::fiber::chain_source(sq.incoming, base_n, sigma, f);
                    let mid = sq.middle;
                    let out_tgt = sq.outgoing.target_degree(mid);
                    // The middle must be squarely in-window; src/target may
                    // fall in the genuinely-empty region (negative s — the
                    // zero map is then real, not missing data), but NOT past
                    // the max_t frontier (there absent data means UNKNOWN,
                    // and reading it as a zero map fakes deficiencies).
                    let edge_ok =
                        |t: Tridegree| -> bool { t.s < 0 || in_window(t) };
                    if !in_window(mid) || !edge_ok(src) || !edge_ok(out_tgt) {
                        continue;
                    }
                    if [src, mid, out_tgt]
                        .iter()
                        .any(|&t| t.s >= 0 && page.is_excluded(t))
                    {
                        continue;
                    }
                    let dim_mid = page.dim_at(mid);
                    if dim_mid == 0 {
                        continue;
                    }
                    let a = page.map_matrix_ref(sq.incoming, src).to_matrix();
                    let b = page.map_matrix_ref(sq.outgoing, mid).to_matrix();
                    let rank_in = mat_rank(&a);
                    let rank_out = mat_rank(&b);
                    let dim_ker_out = dim_mid - rank_out;
                    if dim_ker_out > rank_in {
                        let hidden_at_cell = store
                            .iter()
                            .filter(|hv| {
                                (hv.kind == sq.incoming
                                    && hv.source.degree == src
                                    && hv.target.degree.n == mid.n
                                    && hv.target.degree.s == mid.s)
                                    || (hv.kind == sq.outgoing && hv.source.degree == mid)
                            })
                            .count();
                        out.push(ExactnessDeficiency {
                            base_n,
                            incoming: sq.incoming,
                            outgoing: sq.outgoing,
                            source: src,
                            middle: mid,
                            rank_in,
                            dim_ker_out,
                            deficiency: dim_ker_out - rank_in,
                            hidden_at_cell,
                        });
                    }
                }
            }
        }
    }
    out.sort_by_key(|d| (d.middle.n, d.middle.s, d.middle.f));
    out.dedup_by_key(|d| (d.incoming, d.middle));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::products::ProductKey;

    fn deg(n: i32, s: i32, f: i32) -> Tridegree {
        Tridegree::new(n, s, f)
    }

    fn basis(t: Tridegree, dim: usize, i: usize) -> Element {
        Element::basis(t, dim, i)
    }

    /// The motivating example page from hidden.rs's tests: P(11,13,3) →
    /// (5,17,6), with a product structure allowing one Toda deduction.
    fn toda_page() -> SATPage {
        let mut page = SATPage::new(5);
        page.max_t = Some(60);
        for (t, d) in [
            (deg(11, 13, 3), 1usize),
            (deg(5, 17, 5), 1),
            (deg(5, 17, 6), 1),
            // b at sphere 11+13-2 = 22
            (deg(22, 1, 1), 1),
            (deg(23, 1, 1), 1),
            (deg(24, 1, 1), 1),
            // composites
            (deg(11, 14, 4), 1),
            (deg(5, 18, 7), 1),
            (deg(5, 18, 8), 1),
        ] {
            page.dimension.insert(t, d);
            page.page
                .insert(t, (0..d).map(|i| Element::basis(t, d, i)).collect());
        }
        // E: 22→23→24 identities (dims equal, but store explicitly).
        for (s, t) in [(deg(22, 1, 1), deg(23, 1, 1)), (deg(23, 1, 1), deg(24, 1, 1))] {
            let mut m = mat_zero(1, 1);
            mat_set(&mut m, 0, 0, true);
            let _ = t;
            page.maps.get_mut(&MapKind::E).unwrap().set_matrix(s, m);
        }
        // Products: a∘E²b nonzero, c∘b nonzero.
        page.products.insert(
            ProductKey::new(deg(11, 13, 3), 0, deg(24, 1, 1), 0),
            vec_basis(1, 0),
            1,
            1,
        );
        page.products.insert(
            ProductKey::new(deg(5, 17, 6), 0, deg(22, 1, 1), 0),
            vec_basis(1, 0),
            1,
            1,
        );
        page
    }

    #[test]
    fn solver_contains_v1_closure_and_pins_entries() {
        let page = toda_page();
        let mut store = HiddenStore::new();
        store
            .assert_value(
                &page,
                MapKind::P,
                basis(deg(11, 13, 3), 1, 0),
                basis(deg(5, 17, 6), 1, 0),
            )
            .expect("valid assertion");
        let report = solve_hidden(&page, &store);
        assert!(report.consistent);
        assert!(report.oracle_ok, "oracle failures: {:?}", report.oracle_failures);
        // Assertion + one Toda deduction.
        assert_eq!(report.closure_len, 2, "expected the Toda deduction");
        // Both blocks are 1×1, so both entries are individually determined.
        assert!(
            report
                .determined
                .iter()
                .any(|(v, val)| v.deg == deg(11, 13, 3) && v.delta == 1 && *val),
        );
        assert!(
            report
                .determined
                .iter()
                .any(|(v, val)| v.deg == deg(11, 14, 4) && v.delta == 1 && *val),
        );
    }

    /// Backward reasoning v1 cannot do: a 2-dim source block where two
    /// assertions on overlapping combinations (e0+e1 and e1) determine the
    /// e0-column entries the closure never pins directly.
    #[test]
    fn overlapping_combos_determine_beyond_closure() {
        let mut page = SATPage::new(5);
        page.max_t = Some(60);
        for (t, d) in [(deg(11, 13, 3), 2usize), (deg(5, 17, 5), 1), (deg(5, 17, 6), 1)] {
            page.dimension.insert(t, d);
            page.page
                .insert(t, (0..d).map(|i| Element::basis(t, d, i)).collect());
        }
        let mut store = HiddenStore::new();
        let mut sum = basis(deg(11, 13, 3), 2, 0);
        vec_flip(&mut sum.vec, 1);
        store
            .assert_value(&page, MapKind::P, sum, basis(deg(5, 17, 6), 1, 0))
            .expect("valid");
        store
            .assert_value(
                &page,
                MapKind::P,
                basis(deg(11, 13, 3), 2, 1),
                basis(deg(5, 17, 6), 1, 0),
            )
            .expect("valid");
        let report = solve_hidden(&page, &store);
        assert!(report.consistent);
        assert!(report.oracle_ok);
        // (e0+e1) ↦ 1 and e1 ↦ 1 force e0 ↦ 0 — a value NO closure entry
        // states (v1 knows nothing about e0 alone).
        assert!(report
            .beyond_closure
            .iter()
            .any(|(v, val)| v.col == 0 && v.row == 0 && !*val));
    }

    #[test]
    fn exactness_deficiency_reports_unhit_kernel() {
        // Minimal cell: E: S^4 → S^5 at middle (5,3,2) with dim 1, zero
        // incoming E and zero outgoing H ⇒ rank_in 0 < dim ker_out 1.
        let mut page = SATPage::new(5);
        page.max_t = Some(40);
        for (t, d) in [
            (deg(4, 3, 2), 1usize),
            (deg(5, 3, 2), 1),
            (deg(9, 0, 1), 0),
        ] {
            page.dimension.insert(t, d);
            page.page
                .insert(t, (0..d).map(|i| Element::basis(t, d, i)).collect());
        }
        let store = HiddenStore::new();
        let defs = exactness_deficiencies(&page, &store, 2);
        assert!(
            defs.iter().any(|d| d.middle == deg(5, 3, 2)
                && d.incoming == MapKind::E
                && d.deficiency == 1),
            "expected a deficiency at (5,3,2): {:?}",
            defs
        );
    }
}
